### ISSUE TITLE
Include current pool owner field in SpecialTransactionOutcome::PaydayAccountReward

### ISSUE THREAD

**Issue by bisgardo** [Concordium/concordium-rust-sdk#26]
To resolve the pool owner in a payday account reward (used in Rosetta to resolve the virtual pool accrue address from which the reward is drawn), we currently have to rely on the ordering of the special events and track this information explicitly. This is [documented in the code](https://github.com/Concordium/concordium-rust-sdk/blob/320786bb92d9c02116db71b2818cc7ab6f286dd5/src/types/mod.rs#L617).

See also https://github.com/Concordium/concordium-rust-sdk/pull/21#discussion_r874755226 and https://github.com/Concordium/concordium-rosetta/pull/24#discussion_r895120382.

**Comment by limemloh** [comment]
This sound more like it should be some helper function defined on the type rather than a field.

**Comment by limemloh** [comment]
Status is tracked in https://github.com/Concordium/concordium-rust-sdk/issues/197
